fix(ui): Calendar icon in task listview
frappe/crm pull request #359
Opened 2024-09-19 10:23 UTC by pu-raihan

Calendar icon of Datetime field in task listview was not rendered properly.
This PR fixes it<br><br>
**Before**
<img alt="image" width="468" src="https://github.com/user-attachments/assets/27c9a6c6-a3fa-4ac1-a6f9-0a5b355b9845"/>
**After**
<img alt="image" width="238" src="https://github.com/user-attachments/assets/5ec50be4-945d-477f-85e0-6c37ffda242e"/>

2024-09-19 10:25 UTC, pu-raihan commented
#311 is the issue solved here

2024-09-19 13:57 UTC, shariquerik requested changes

2024-09-19 13:57 UTC, shariquerik commented on frontend/src/components/ListViews/TasksListView.vue
> +              </div>
```suggestion
              <div><CalendarIcon /></div>
```

2024-09-19 13:57 UTC, shariquerik commented on frontend/src/components/ListViews/TasksListView.vue
>            <Tooltip :text="dateFormat(item, 'ddd, MMM D, YYYY | hh:mm a')">
```suggestion
          <Tooltip
            :text="item && dateFormat(item, 'ddd, MMM D, YYYY | hh:mm a')"
          >
```

Only show tooltip if date is set

2024-09-19 13:57 UTC, shariquerik commented on frontend/src/components/ListViews/TasksListView.vue
> +    () => listBulkActionsRef.value?.customListActions
```suggestion
    () => listBulkActionsRef.value?.customListActions,
```

2024-09-20 05:16 UTC, pu-raihan commented
@shariquerik I have made the requested changes

2024-09-20 05:25 UTC, shariquerik approved these changes

2024-09-20 05:26 UTC, merged